core:
  name: robodev
  user: hsr
  password: asimov
disks:
  main:
    size: 10G
    partitions:
      swap:
        filesystem: swap
        mount_point: SWAP
        mount_options: defaults
        size: 1G
      root:
        filesystem: ext4
        mount_point: ROOT
        mount_options: rw,noatime,nodiratime,data=ordered,discard
        size: REMAINING
        script:
          - sudo systemctl enable ros2-daemon.service
          - sudo systemctl enable sshd.service
          - sudo ldconfig
packages:
  official:
    - openssh
    - ros2
    - clang
    - tinc
  aur:
    - visual-studio-code-insiders
