core:
  name: robodev
  user: hsr
  password: asimov
disks:
  main:
    size: 10G
    partitions:
      swap:
        filesystem: swap
        mount_point: SWAP
        mount_options: defaults
        size: 1G
      root:
        filesystem: ext4
        mount_point: ROOT
        mount_options: rw,noatime,nodiratime,data=ordered,discard
        size: REMAINING
packages:
  official:
    - clang
    - gpsd
    - i2c-tools
    - openssh
    - open-vm-tools
    - tinc
  aur:
    - conan
    - ros2
    - visual-studio-code-bin
    - xpadneo-dkms
scripts:
  ENABLE_ROS2_SERVICE:
    - sudo systemctl enable ros2-daemon.service
  ENABLE_SSH_SERVICE:
    - sudo systemctl enable sshd.service
  EXECUTE_LDCONFIG:
    - sudo ldconfig
